layout:
  rowSizes:
  - 2
  - 2
  centerEachRow: false
clocks:
- heading: New York
  zone: America/New_York
  color: blue
- heading: Kabul
  zone: Asia/Kabul
  color: black
- heading: Kolkata
  zone: Asia/Kolkata
  color: cyan
- heading: Perth
  zone: Australia/Perth
  color: magenta
live: false
seconds: false
