dateFormat: "15:04"
layout:
  rowSizes:
  - 1
  centerEachRow: true
timezones:
- heading: New York
  zone: America/New_York
  color: blue
- heading: Kabul
  zone: Asia/Kabul
  color: black
- heading: Kolkata
  zone: Asia/Kolkata
  color: cyan
