dateFormat: "15:04"
rowSizes:
- 2
- 3
timezones:
- heading: New Delhi
  zone: Asia/Kolkata
  color: red
- heading: Tirane
  zone: Europe/Tirane
  color: blue
- heading: Algiera
  zone: Africa/Algiers
  color: green
centerEachRow: true
