layout:
  rowSizes:
  - 2
  - 1
  centerEachRow: true
clocks:
- heading: New York
  zone: America/New_York
  color: blue
- heading: Kolkata
  zone: Asia/Kolkata
  color: cyan
- heading: Perth
  zone: Australia/Perth
  color: magenta
live: false
seconds: false
