dateFormat: "15:04"
rowSizes:
  - 2
  - 3
timezones:
  - heading: Kolkata
    zone: Asia/Kolkata
    color: green
  - heading: New York
    zone: America/New_York
    color: green
centerEachRow: true
