on:
  push:
    paths: ["cmd/version.txt"]
    branches: ["main", "fix-ci"]

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # required for the changelog to work correctly.
      - name: Tag
        id: tag
        run: |
          echo "TAG=$(head -c -1 cmd/version.txt)" >> $GITHUB_ENV

      - name: Create Tag
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/v' + process.env.TAG,
              sha: context.sha
            })

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.3"
      - name: build
        run: make dist

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: $TAG
          release_name: Release v$TAG
          body: Release description
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Assets to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/*
          asset_name: dist-$TAG
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
